#!/bin/bash

set -e

. tests/framework

SNAPPY=snappy-go

MYDIR=$(dirname $0)
for test in $MYDIR/tests/*_test_*; do
    CURRENT_TEST=$(basename $test)

    # after a reboot, skip ahead to the test that triggered it
    if [ -n "$ADT_REBOOT_MARK" ]; then
        if [ "$ADT_REBOOT_MARK" == "$CURRENT_TEST" ]; then
            echo "Resuming $test after reboot"
        else
            continue
        fi
    else
        echo "Running $test"
    fi

    . "$test"
    if ! (test 2>&1); then
        echo "FAILED: $test"
        exit 1
    fi

    # clear reboot marker
    unset ADT_REBOOT_MARK
done
