#!/bin/sh

set -e

fail() {
    echo "ERROR"
    exit 1
}

test_equal() {
    echo "$1" > $TMPDIR/want
    shift
    "$@" 2>&1 > $TMPDIR/got
    if ! diff -u $TMPDIR/want $TMPDIR/got; then
        fail
    fi
}

test_regexp() {
    REGEXP="$1"
    shift
    "$@" 2>&1 > $TMPDIR/got
    if ! grep -E -q "$REGEXP" $TMPDIR/got; then
        echo "Can not find '$REGEXP' in '$(cat $TMPDIR/got)'"
        fail
    fi
}


TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
for test in tests/test_*; do
    echo "Running $test"
    . "$test"
    if ! test ; then
        echo "FAILED: $test"
        exit 1
    fi
done
